apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo-service
  name: demo-service
spec:
  ports:    
    - port: 80
      targetPort: 8080  
  selector:
    app: demo-app
  type: LoadBalancer